# Generated by Django 4.1.10 on 2023-09-06 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0022_auto_20230605_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftplog',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='action',
            field=models.CharField(choices=[('view', 'Visualizar'), ('update', 'Atualizar'), ('delete', 'Apagar'), ('create', 'Criar'), ('download', 'Download'), ('connect', 'Conectar'), ('login', 'Login'), ('change_password', 'Alterar Senha'), ('accept', 'Aceitar'), ('review', 'Analisar'), ('notice', 'Notificações'), ('reject', 'Recusar'), ('approve', 'Aprovar'), ('close', 'Fechar')], max_length=16, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de login'),
        ),
    ]
